FROM ubuntu:24.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential cmake git ca-certificates \
    libssl-dev libboost-all-dev libevent-dev libminiupnpc-dev \
    pkg-config qt6-tools-dev-tools qt6-tools-dev && \
    rm -rf /var/lib/apt/lists/*

ARG FLOWEE_VERSION=2024.01.0
WORKDIR /build
RUN git clone --depth 1 --branch ${FLOWEE_VERSION} \
    https://codeberg.org/Flowee/thehub.git

WORKDIR /build/thehub/build
RUN cmake -Dbuild_apps=ON CMakeLists.txt .. && \
    make -j"$(nproc)" hub hub-cli indexer
